# Generated by Django 4.0.5 on 2022-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_details_email_alter_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
