# Generated by Django 3.2.16 on 2022-11-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_location_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='Detail',
        ),
    ]
