# Generated by Django 4.1.2 on 2022-12-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image_url',
        ),
        migrations.AddField(
            model_name='location',
            name='image1',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image2',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image3',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image4',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
    ]
