# Generated by Django 4.1.2 on 2022-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_location_image_url_location_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image1',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image2',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image3',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image4',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
    ]
