# Generated by Django 4.1.2 on 2022-12-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_location_image1_alter_location_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image4',
        ),
    ]
