# Generated by Django 4.1.2 on 2022-12-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_image1_location_image_remove_location_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='image',
            new_name='image_url',
        ),
    ]
