# Generated by Django 4.1.2 on 2022-12-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_image_location_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='location',
            name='price',
        ),
    ]
