# Generated by Django 5.0.4 on 2024-06-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
